### ISSUE TITLE
Server compilation

### ISSUE THREAD

**Issue by LifeGold** [emperorstarfinder/My-Halcyon#18]
Hello. You can write a step-by-step instruction on how to compile and run the server under Windows Server 2012

**Comment by emperorstarfinder** [comment]
@LifeGold Hi there.  

Yes a compilation and configuration guide will be written.  This also will be very similar to Virtual Universe Version 2.0 which is in current active development.  It will mirror the Second Galaxy Development Team's GalaxyGrid architecture which works the same way this does and is compatible.  

Which will help you run an even more stable and secure grid using Virtual Universe which as you know is the Second Galaxy Development Team's Open Source Project Arm.  

This repository is more for experimentation with ideas to help ensure there is a stable architecture compatible with all grids.
